/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChallengeSession {
  'user' : Principal,
  'timestamp' : bigint,
  'xpEarned' : bigint,
}
export type ICPAmount = bigint;
export interface ICPTransaction {
  'to' : string,
  'status' : string,
  'from' : string,
  'timestamp' : bigint,
  'amount' : ICPAmount,
}
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'accountId' : string,
  'isAdmin' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<[string], UserProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterAccountId' : ActorMethod<[], [] | [string]>,
  'getCompetitionState' : ActorMethod<[], boolean>,
  'getFirstUserFlag' : ActorMethod<[], [] | [Principal]>,
  'getLeaderboard' : ActorMethod<[], Array<[string, bigint]>>,
  'getTransactionHistory' : ActorMethod<[], Array<ICPTransaction>>,
  'getUserChallengeSessions' : ActorMethod<[], Array<ChallengeSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveChallengeSession' : ActorMethod<[bigint], undefined>,
  'setCanisterAccountId' : ActorMethod<[string], undefined>,
  'setCompetitionState' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];