/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'accountId' : IDL.Text,
  'isAdmin' : IDL.Bool,
});
export const ICPAmount = IDL.Nat64;
export const ICPTransaction = IDL.Record({
  'to' : IDL.Text,
  'status' : IDL.Text,
  'from' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : ICPAmount,
});
export const ChallengeSession = IDL.Record({
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'xpEarned' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterAccountId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCompetitionState' : IDL.Func([], [IDL.Bool], ['query']),
  'getFirstUserFlag' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(ICPTransaction)], ['query']),
  'getUserChallengeSessions' : IDL.Func(
      [],
      [IDL.Vec(ChallengeSession)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveChallengeSession' : IDL.Func([IDL.Int], [], []),
  'setCanisterAccountId' : IDL.Func([IDL.Text], [], []),
  'setCompetitionState' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'accountId' : IDL.Text,
    'isAdmin' : IDL.Bool,
  });
  const ICPAmount = IDL.Nat64;
  const ICPTransaction = IDL.Record({
    'to' : IDL.Text,
    'status' : IDL.Text,
    'from' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : ICPAmount,
  });
  const ChallengeSession = IDL.Record({
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'xpEarned' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterAccountId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCompetitionState' : IDL.Func([], [IDL.Bool], ['query']),
    'getFirstUserFlag' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(ICPTransaction)],
        ['query'],
      ),
    'getUserChallengeSessions' : IDL.Func(
        [],
        [IDL.Vec(ChallengeSession)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveChallengeSession' : IDL.Func([IDL.Int], [], []),
    'setCanisterAccountId' : IDL.Func([IDL.Text], [], []),
    'setCompetitionState' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };